- name: Add repository
  yum_repository:
    name: epel
    description: "EPEL YUM repo"
    baseurl: "http://download.fedoraproject.org/pub/epel/7/x86_64/"
    gpgcheck: no


- name: Install System Tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - vim
    - gcc
