- name: Install System Tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nc
    - telnet
    - vim
    - unzip
    - python-setuptools

- name: Install Python Pip
  shell: >
    easy_install pip
  become: true

- name: Install Python Packages
  pip:
    name: "{{ item }}"
  with_items:
    - requests
    - argparse
    - logging
    - PyYAML
  become: true
